# Generated by Django 3.0.1 on 2020-01-01 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('time_status', models.CharField(choices=[('ON_TIME', 'On Time'), ('DELAYED', 'Delayed'), ('CANCELED', 'Canceled')], default='ON_TIME', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('locking_reason', models.CharField(choices=[('NONE', 'None'), ('UNOPENED', 'Unopened'), ('EVENT_CANCELED', 'Event Canceled'), ('REG_CLOSED', 'Reg Closed')], default='NONE', max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('is_fcfs', models.BooleanField(default=False, verbose_name='FCFS')),
                ('start_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('demand', models.IntegerField(default=1, help_text='number of members needed')),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
