# Generated by Django 3.0.1 on 2019-12-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('time_status', models.CharField(choices=[('ON_TIME', 'On time'), ('DELAYED', 'Delayed'), ('CANCELED', 'Canceled')], max_length=255)),
                ('event_start_at', models.DateTimeField()),
                ('event_ended_at', models.DateTimeField()),
                ('register_start_at', models.DateTimeField()),
                ('result_release_at', models.DateTimeField()),
                ('register_ended_at', models.DateTimeField()),
            ],
        ),
    ]
