# Generated by Django 3.0.1 on 2020-01-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locking_reason',
            field=models.CharField(choices=[('NONE', 'None'), ('UNOPENED', 'Unopened'), ('EVENT_CANCELED', 'Event Canceled'), ('REG_CLOSED', 'Registration closed')], default='NONE', max_length=255),
        ),
    ]
