# Generated by Django 3.0.1 on 2019-12-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_status',
            field=models.CharField(choices=[('ON_TIME', 'On time'), ('DELAYED', 'Delayed'), ('CANCELED', 'Canceled')], default='ON_TIME', max_length=255),
        ),
    ]
