# Generated by Django 3.0.1 on 2020-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200103_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='status',
            field=models.CharField(choices=[('NONE', 'Unregistered'), ('PENDING', 'Registration pending'), ('ACCEPTED', 'Registration accepted'), ('REJECTED', 'Registration rejected')], default='PENDING', max_length=255),
        ),
    ]
