# Generated by Django 3.0.1 on 2019-12-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_ended_at',
            new_name='ended_at',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start_at',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='register_ended_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='register_start_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='result_release_at',
        ),
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_fcfs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
