# Generated by Django 3.0.1 on 2019-12-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191231_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_status',
            field=models.CharField(choices=[('ON_TIME', 'On Time'), ('DELAYED', 'Delayed'), ('CANCELED', 'Canceled')], default='ON_TIME', max_length=255),
        ),
    ]
