# Generated by Django 3.0.1 on 2020-01-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_weekconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekconfig',
            name='reg_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weekconfig',
            name='reg_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
