# Generated by Django 3.0.1 on 2019-12-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191231_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='week',
            field=models.CharField(choices=[('NONE', 'None'), ('WEEK_0', 'Week 0'), ('WEEK_1', 'Week 1'), ('WEEK_2', 'Week 2'), ('WEEK_3', 'Week 3'), ('WEEK_4', 'Week 4'), ('WEEK_5', 'Week 5')], default='NONE', max_length=255),
        ),
    ]
