# Generated by Django 3.0.1 on 2020-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
