# Generated by Django 3.0.1 on 2019-12-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manpower',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_fcfs',
            field=models.BooleanField(default=False, verbose_name='First come first serve'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
