# Generated by Django 3.0.1 on 2020-01-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_announcement_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='custom_tags',
            field=models.ManyToManyField(to='events.Tag'),
        ),
    ]
