# Generated by Django 3.0.1 on 2019-12-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191231_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_fcfs',
            field=models.BooleanField(default=False, verbose_name='FCFS'),
        ),
    ]
