# Generated by Django 3.0.1 on 2020-01-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20191231_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='week',
        ),
    ]
