# Generated by Django 3.0.1 on 2020-01-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200107_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], default='INFO', max_length=255),
        ),
    ]
