# Generated by Django 3.0.1 on 2020-01-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200109_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_inconsistent',
            field=models.BooleanField(default=False),
        ),
    ]
