# Generated by Django 3.0.1 on 2020-01-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='readonly',
            new_name='locked',
        ),
    ]
