# Generated by Django 3.0.1 on 2020-01-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200101_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locking_reason',
            field=models.CharField(choices=[('NONE', 'None'), ('UNOPENED', 'Unopened'), ('EVENT_CANCELED', 'Event Canceled'), ('OTHER', 'Other')], default='NONE', max_length=255),
        ),
    ]
