# Generated by Django 3.0.1 on 2020-01-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_is_inconsistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
