# Generated by Django 3.0.1 on 2020-01-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_locking_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='demand',
            field=models.IntegerField(default=1, help_text='number of members needed'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locking_reason',
            field=models.CharField(choices=[('NONE', 'None'), ('UNOPENED', 'Unopened'), ('EVENT_CANCELED', 'Event Canceled'), ('REGISTRATION_CLOSED', 'Registration Closed')], default='NONE', max_length=255),
        ),
    ]
