# Generated by Django 3.0.1 on 2020-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekconfig',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
